### PR TITLE
Disable AsciiDocIT on wildfly.

### PR DESCRIPTION
**Pull request by erdlet**
see: #70
Signed-off-by: Erdle, Tobias <tobias.erdle@innoq.com>

### CODE REVIEW

**Comment by erdlet** [comment]
Always happy to help :)

**Comment by chkal** [comment]
Thanks a lot, looks great. As mentioned in the other pull request, I would like to wait a bit with merging this, so we can do the bulk-update of the copyright headers before.

One minor thing: Could you perhaps add a comment to the `@Category(IgnoreOnWildfly.class)` lines explaining why we are ignoring these tests on Wildfly? Just to make sure that we remember the reason in a few years. :laughing:

**Comment by erdlet** [comment]
Sure makes sense. I'll add comments on these tests :)

**Comment by chkal** [comment]
Unfortunately getting approval for the update of the copyright headers takes longer than expected. So I'll start to merge a few of the pending pull requests and rebase my branch for the header update.

Sorry for the delay... :disappointed:

**Pull request merged**
