### PR TITLE
update version docker Payara 5.191

### PR DESCRIPTION
**Pull request by Daniel-Dos**
Signed-off-by: Daniel Dias <daniel.dias.analistati@gmail.com>

this PR does an update in payara docker

### CODE REVIEW

**Comment by chkal** [comment]
Hey @Daniel-Dos. Thanks a lot for the PR. But for some reason the tests are failing now. Looks like some SSL problem. Any idea what is causing this? Maybe a Travis issue? Or did Payara update their default certificate?

**Comment by gtudan** [comment]
Yeah, sorry about that. They seem to generate the keypair during the release, which means it has to be updated all the time. Should have mentioned that in the docker script.

I didn‘t find an easy way to disable the certificate validation in the arquillian payara provider without hacking to deep into it and the docker image doesn’t expose the admin API over plain HTTP.

**Comment by chkal** [comment]
@gtudan Ah, ok. Thanks for the info. How do you update the certificate?

**Comment by chkal** [comment]
Ah, found it:

https://github.com/eclipse-ee4j/krazo/blob/9abdc61445b62613634d6c3058c85b8b3adbec63/testsuite/pom.xml#L245-L261

Maybe we should add a comment to the pom.xml fragment describing how to update the certificate store.

**Comment by gtudan** [comment]
Will do 😊

**Comment by Daniel-Dos** [comment]
Hi,

Do I have to comment on informed lines?

**Comment by gtudan** [comment]
Sorry @Daniel-Dos, I couldn't update your branch, so I created a new PR #62.

It also contains instructions on how to import the certifcate to the truststore for future updates.

**Comment by chkal** [comment]
Closing this in favor of #62

**Pull request closed without merging**
