### PR TITLE
Reactivate Pebble extension

### PR DESCRIPTION
**Pull request by erdlet**
Please don't merge before the version update. Needs to be done here manually.

closes: #234

### CODE REVIEW

**Review by chkal — CHANGES_REQUESTED** [review]
We should reactivate the integration test for the Pebble extension as well if possible.

See:

https://github.com/eclipse-ee4j/krazo/blob/a47b665e223ec54ecf7758bcc0ec64ad827c4317/testsuite/src/test/java/org/eclipse/krazo/test/ext/PebbleIT.java#L40

**Comment by erdlet** [comment]
> We should reactivate the integration test for the Pebble extension as well if possible.
> 
> See:
> 
> https://github.com/eclipse-ee4j/krazo/blob/a47b665e223ec54ecf7758bcc0ec64ad827c4317/testsuite/src/test/java/org/eclipse/krazo/test/ext/PebbleIT.java#L40

Ah thanks, I‘ve not recognized the test. I‘ll reactivate later.

**Comment by chkal** [comment]
> Ah thanks, I‘ve not recognized the test. I‘ll reactivate later.

Awesome! Thanks.

**Review by gtudan — APPROVED** [review]

**Comment by erdlet** [comment]
I tested the IT against Wildfly on my notebook and it worked perfectly.

**Review by chkal — APPROVED** [review]

**Pull request merged**
