### PR TITLE
Provide default features for implementation who need to register them manually

### PR DESCRIPTION
**Pull request by lefloh**
During the review of @erdlet's documentation PR I saw that's currently quite cumbersome to set up Krazo with CXF. We could make it easier by providing all default features.

### CODE REVIEW

**Comment by lefloh** [comment]
I updated `_quickstart.adoc`. What did I forgot?

**Comment by erdlet** [comment]
Ah sorry, I misread the name of the changed file. Then everything is fine :)

Florian Hirsch <notifications@github.com> schrieb am Sa., 11. Apr. 2020,
14:34:

**Comment by lefloh** [comment]
Good idea @chkal! I renamed the constant to `PROVIDERS`.

**Comment by chkal** [comment]
> Good idea @chkal! I renamed the constant to `PROVIDERS`.

Awesome! Thanks!

**Pull request merged**
