### PR TITLE
Run the testsuite against the lastest WF-Release (17)

### PR DESCRIPTION
**Pull request by gtudan**
This updates the testsuite to the latest Wildfly version. 
The good news: no regressions \o/. Sad news: still some issues with module loading with jruby/jython.

### CODE REVIEW

**Comment by chkal** [comment]
Thanks @gtudan.

But it looks like Travis is failing. I'll restart the job and see if this fixes the problem.

**Comment by chkal** [comment]
I just realized that the build is failing, because I forgot to merge #72. Sorry about that: :disappointed: 

@gtudan Could you rebase this one against master? Unfortauntely the branch protection settings don't allow us to merge pull requests with failed checks.

**Comment by gtudan** [comment]
@chkal Done, the tests should pass now.

**Comment by chkal** [comment]
Awesome. Thanks.

**Pull request merged**
