### PR TITLE
Check all dependencies for updates and update them

### PR DESCRIPTION
**Pull request by dmaidaniuk**
Added `versions-maven-plugin` for automatic dependencies versions checking during the build. Use Maven phase `verify` for this purpose.

### CODE REVIEW

**Comment by erdlet** [comment]
Hi @dmaidaniuk,

thanks a lot for this PR. To be able to submit this changes, you'll need to sign the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) from within your Eclipse Account. 

After that, I (or someone else) needs to create the necessary paperwork for upgrading some of the libs. I'll keep you updated about the status of this paperwork.

**Comment by erdlet** [comment]
CQs required for:

- Easymock 4.2 -> 4.3
- HtmlUnit 2.36 -> 2.55
- asciidoctorj 2.0.0 -> 2.5.2
- ST4 4.2 -> 4.3.1
- velocity 2.1 -> 2.3
- RESTEasy 3.13.2 -> 3.15.2

@ivargrimstad Do we need CQs for minor version changes in `jakarta` Maven artifacts, like Jakarta EE 9.0.0 -> Jakarta EE 9.1.0?

**Review by erdlet — APPROVED** [review]
Looks good to me. Only the CQs need to be created and approved.

**Comment by dmaidaniuk** [comment]
Hi @erdlet ,
My signed ECA is here: https://accounts.eclipse.org/user/591583/eca/3.1.0

**Comment by erdlet** [comment]
@dmaidaniuk thanks for the signature. The bot already registered it :)

I hope I'll find the time for the CQs within the next days. I'll update the PR as soon as I created them.

**Comment by erdlet** [comment]
@ivargrimstad thanks for the hint to use the dash-license tool. I ran it over all changed `pom.xml` files and there is no need to file a CQ for any of the changed libs :muscle:

**Comment by erdlet** [comment]
So for me this is fine now. I ran the testsuite against WildFly on JDK 11 and 17 as well as Glassfish 6.2.2 on JDK 11 and 17 and everything is fine.

@dmaidaniuk thanks again! :)

**Pull request merged**
