### PR TITLE
Fixed broken Pebble Templates link in README.md.

### PR DESCRIPTION
**Pull request by vsmid**

### CODE REVIEW

**Comment by vsmid** [comment]
I signed ECA. I think checks should now pass.

**Comment by erdlet** [comment]
Hi @vsmid 

thanks for your contribution! Please sign off your commit with the email address used in the ECA to get the check passed. You can have a look into our contribution guidelines for more information on that :)

**Comment by vsmid** [comment]
Is there any other way to signoff other than force push to my fork master after I singoff ?

**Comment by erdlet** [comment]
Unfortunately, I'm not aware of any other solution :/

**Comment by vsmid** [comment]
Ok, thanks, this extension was my contribution before Jakarta. There are some things that will need some updating. I will try to update this extension as I find spare time.

**Comment by erdlet** [comment]
Thanks in advance for your effort! I'll merge this PR as soon as the pipeline is successful

**Comment by chkal** [comment]
@vsmid Thanks a lot! :beers:

**Pull request merged**
