### PR TITLE
131 annotation support for converter registry

### PR DESCRIPTION
**Pull request by erdlet**

### CODE REVIEW

**Comment by erdlet** [comment]
Seems the patched Glassfish makes some trouble.

`org.jboss.arquillian.container.spi.client.container.LifecycleException: Could not connect to DAS on: http://localhost:4848 | Unexpected end of file from server`

I don't have any idea what this could be, so is there someone who saw this problem before?

**Comment by chkal** [comment]
> I don't have any idea what this could be, so is there someone who saw this problem before?

I saw something similar if Glassfish didn't startup correctly. I'll restart the job. Let's see if this fixes the problem.

**Comment by chkal** [comment]
The build is back to green. Seems like this was a temporary issue. I'll review the PR ASAP.

**Comment by erdlet** [comment]
Thanks for your review!

Yeah good idea, I'll add this parameter on monday.

Christian Kaltepoth <notifications@github.com> schrieb am Sa., 18. Jan.
2020, 09:56:

**Comment by chkal** [comment]
> Yeah good idea, I'll add this parameter on monday.

Awesome! Do you want to add this to the current PR or should we merge this one and you create a new one. I'm fine with both options. :-)

**Comment by erdlet** [comment]
I'd add this to the current PR. Shouldn't be much effort to add and test
it, so an additional PR is much bureaucracy for me :)

Christian Kaltepoth <notifications@github.com> schrieb am Sa., 18. Jan.
2020, 10:11:

**Comment by chkal** [comment]
Looks great! Thanks a lot! I'll wait a day or two with merging. Maybe we get more feedback!?

**Comment by erdlet** [comment]
Would be great to get some more feedback :+1:

**Comment by erdlet** [comment]
Thanks a lot!

> This would be an ideal addition to our upcoming user guide (wink wink).

Great idea. I hope to find some time the next days to add documentation for the hidden method filter and this one :)

**Pull request merged**
