### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by ivargrimstad**
Merge release branch into master after release

### CODE REVIEW

**Comment by ivargrimstad** [comment]
@chkal Any idea why Travis wants to download these from Apache for some of the tests?

```
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/eclipse/krazo/krazo-core/2.0.0-SNAPSHOT/maven-metadata.xml
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/eclipse/krazo/krazo-core/2.0.0-SNAPSHOT/krazo-core-2.0.0-SNAPSHOT.pom
[WARNING] The POM for org.eclipse.krazo:krazo-core:jar:2.0.0-SNAPSHOT is missing, no dependency information available
```

**Comment by erdlet** [comment]
Hi @ivargrimstad,
I face the same issue in #207 where @chkal had an idea how to fix it. Maybe you can try this approach here?

**Comment by ivargrimstad** [comment]
DID IT!
I think I will commit the entire history here and not squash it to save for the history how painful it was :)

**Review by erdlet — APPROVED** [review]

**Comment by erdlet** [comment]
Nice, thanks for fixing the pipeline! 🍻

**Review by chkal — COMMENTED** [review]
Late +1

**Pull request merged**
